# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('firebase_key.json', '.'),
        ('cafe.db', '.'),
        ('CoffeRoom.ico', '.'),
        ('coffee_theme.json', '.'),
        ('state.py', '.'),
        ('modules', 'modules'),
        ('static', 'static'),
        ('barcodes', 'barcodes'),
        ('modules/qr_codes', 'modules/qr_codes'),
    ],
    hiddenimports=[
        'customtkinter',
        'firebase_admin',
        'firebase_admin.credentials',
        'firebase_admin.firestore',
        'firebase_admin.messaging',
        'PIL',
        'sqlite3',
        'tkinter',
        'threading',
        'requests',
        'qrcode',
        'flask',
        'packaging',
        'packaging.version',
        'calendar',
        'collections',
        'google.cloud.firestore',
        'google.cloud.firestore_v1',
        'google.api_core',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='CoffeRoom',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='CoffeRoom.ico',
)
